[colors.bright]
black = '0x727169'
red = '0xe82424'
green ='0x98bb6c'
yellow = '0xe6c384'
blue = '0x7fb4ca'
magenta = '0x938aa9'
cyan = '0x7aa89f'
white = '0xdcd7ba'

#black = "0x575860"
#blue = "0x86abdc"
#cyan = "0x7ad5d6"
#green = "0x8ebaa4"
#magenta = "0xbaa1e2"
#red = "0xd16983"
#white = "0xe4e4e5"
#yellow = "0xe0c989"

[colors.normal]
black = '0x090618'
red = '0xc34043'
green = '0x76946a'
yellow ='0xc0a36e'
blue = '0x7e9cd8'
magenta = '0x957fb8'
cyan = '0x6a9589'
white = '0xc8c093'

#black = "0x393b44"
#blue = "0x719cd6"
#cyan = "0x63cdcf"
#green = "0x81b29a"
#magenta = "0x9d79d6"
#red = "0xc94f6d"
#white = "0xdfdfe0"
#yellow = "0xdbc074"

[colors.primary]
background = '0x1f1f28'
foreground = '0xdcd7ba'

#background = "0x011627"
#foreground = "0xcdcecf"

[colors.selection]
background = '0x2d4f67'
foreground ='0xc8c093'

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.normal]
family = "Consolas"


